version: "3.1"
#
# Optional Volumes:
#  - /opt/phabricator/conf - configuration
#  - /var/repo - code repos
#
#
services:
  phabricator:
      build: .
      links: ['database']
      ports: ['8081:80']


  database:
      build: database/
